### ISSUE TITLE
Parameters for registering a perspective transformed image

### ISSUE THREAD

**Issue by WhaSukGO** [biomedia-mira/drop2#10]
First of all, thank you for such a marvelous work!

I have a question regarding the parameters.

I'm trying to register 2D perspective-tranformed images to a given template.

For example, in the image below, I'm trying to register image on the left to template (which is on the right)

![Example](https://answers.opencv.org/upfiles/14331120304698347.png)
(The image is from [here](https://answers.opencv.org/question/62956/perspective-transform-using-chessboard/))

No extra transformation is needed, but only homography is required.

Is it possible to estimate the parameters of homography via this project? If so, could you provide some tips on how to set the parameters?

Thank you!

**Comment by bglocker** [comment]
Thanks for the kind feedback.

I'm afraid drop2 has no projective transformation model implemented. The linear registration models are currently limited to rigid, similarity, and affine. As drop2 is primarily used in the context of medical image registration, there has been no need for projective transformations, so far.

**Comment by WhaSukGO** [comment]
I see. Thank you again! By the way, may I ask if there's any algorithm for registering projective transformed images?

**Comment by bglocker** [comment]
I would suggest to check out [OpenCV](https://opencv.org/)
