### ISSUE TITLE
Output Images Lost Color + Massive Warping

### ISSUE THREAD

**Issue by jlevy44** [biomedia-mira/drop2#4]
Hi there, great package!

I seem to be having problems though with the image output, for some reason, the output images that I am getting are in black in white rather than color. What can I do to remedy this issue?

I'm studying histology specimen, but there seems to be massive warping if the tissue is broken up into sections and I try to fit multiple sections to each other.

**Comment by jlevy44** [comment]
For some reason the color is lost during the processing. Would much appreciate help!

**Comment by Borda** [comment]
the warping uses only grey-scale images, see [BIRL example](https://github.com/Borda/BIRL/blob/master/bm_experiments/bm_DROP2.py#L37-L43)

**Comment by jlevy44** [comment]
Sure, just wanted to verify. Do you know of any packages that register with color? Or without color but map the pixels? 

In fact is there somewhere where you record the affine transforms applied?

Thanks!

**Comment by Borda** [comment]
yes, you can get that deformation field so you can do the image warping by yourself...

**Comment by jlevy44** [comment]
What option do I need to use to output the deformation field?

**Comment by Borda** [comment]
see the example here - https://birl.readthedocs.io/en/latest/bm_experiments.bm_DROP2.html

**Comment by jlevy44** [comment]
Thanks!
