### ISSUE TITLE
Applying transform on grayscale image

### ISSUE THREAD

**Issue by asmagen** [biomedia-mira/drop2#7]
I was trying to apply the deformation field transformation on a grayscale image (one of the deconvolved channels of an image) using the transform function here, but although I provide what appears to be necessary (source and output), it still requires the target for some reason.

Can you please clarify how to use the transform functionality?

Thanks

**Comment by bglocker** [comment]
The target is still required as it defines the output space (image resolution, voxel size, origin, etc.) for the warped source image.

**Comment by asmagen** [comment]
Thanks
