### ISSUE TITLE
Cannot use values in transform.txt to get the same deformed image

### ISSUE THREAD

**Issue by JarveeLee** [biomedia-mira/drop2#8]
After register source image to target image using linear transformation only ,  trasnform.png and transform.txt is generated. I read the values and use it as the matrix to transform the mask of source , but can not get the transformed mask to fit transform.png

this is a 2D image code that i use: 

import cv2,os
source_mask = cv2.imread('source_mask.png',0)
target_mask = cv2.imread('target_mask.png',0)
source = cv2.imread('source.png')
target = cv2.imread('target.png')
order = './dropreg --mode2d -s source_mask.png -t target_mask.png -o transform_mask.png -l --llevels 4 4 1 2 2 1 --lsim 1 --lsampling 0.2'
os.system(order)
f = open('transform_mask_transform.txt','r').readlines()
matrix = [
    [float(f[0].strip().split('\t')[0]) , -float(f[0].strip().split('\t')[1]) , -float(f[0].strip().split('\t')[3]) ],
    [-float(f[1].strip().split('\t')[0]) , float(f[1].strip().split('\t')[1]) , -float(f[1].strip().split('\t')[3]) ],
]
matrix = np.array(matrix)
transform_image = cv2.warpaffine(source,matrix,(target.shape[0],target.shape[1]))

but visually transform_image can not fit transform_mask. I don't know why.

**Comment by bglocker** [comment]
I am not sure how OpenCV's `warpaffine` function works exactly and what input it expects for the affine matrix. Note, you can also use `dropreg` directly to warp additional images by passing the resulting transformation as a parameter (and discarding everythin after `-l`).

Alternatively, would you mind posting some screenshots of the warped image that you get with OpenCV?

**Comment by JarveeLee** [comment]
target image

![5_he](https://user-images.githubusercontent.com/21051247/85360596-1b657f80-b54c-11ea-84f5-7159b0054ff8.jpg)


the parameters in transform.txt 

0.957389	-0.288803	0	673.645
0.288803	0.957389	0	-455.5
0	0	1	0
0	0	0	1

source image 
![5_ihc](https://user-images.githubusercontent.com/21051247/85360616-26b8ab00-b54c-11ea-8789-751eed9e1d79.jpg)


transformed image generated by drop2
![5_ihc_op](https://user-images.githubusercontent.com/21051247/85360627-2cae8c00-b54c-11ea-9feb-bca0324cd629.jpg)



using parameters from transform.txt and use cv2.warpAffine , generate this image
![5_ihc_transform](https://user-images.githubusercontent.com/21051247/85360636-32a46d00-b54c-11ea-85ee-ae35b6f84b68.jpg)



rotation and scale seem to be correct but the position is slightly wrong.
I hope to use cv2.warpAffine because is can process faster inside the code, without more os.system(order) ......
Or do you know some other function that can use values and transform image inside code ?

**Comment by bglocker** [comment]
Just looking at your code snippet

`matrix = [
[float(f[0].strip().split('\t')[0]) , -float(f[0].strip().split('\t')[1]) , -float(f[0].strip().split('\t')[3]) ],
[-float(f[1].strip().split('\t')[0]) , float(f[1].strip().split('\t')[1]) , -float(f[1].strip().split('\t')[3]) ],
]`

Is there a specific reason why you negate some of the values?

**Comment by JarveeLee** [comment]
because I guess the rotation angle, position shift in drop2 is opposite to those in cv2.warpAffine, and this is the most similar generated results of drop2 and cv2.warpAffine....

**Comment by bglocker** [comment]
Looking at the doc of [`warpAffine`](https://docs.opencv.org/2.4/modules/imgproc/doc/geometric_transformations.html?highlight=warpaffine#warpaffine) you may need to set the flag `WARP_INVERSE_MAP` and pass the values from the transformation as is (no negation), because drop2 is already giving you the inverse transformation to be used in backward warping.
